Console.Clear();
Console.WriteLine("Welcome to Himni and Harry's dungeon! \n 0) Load game \n 1) New game");
Console.ReadKey();
Console.Clear();

Console.WriteLine("Game loading");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading.");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading..");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading...");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading.");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading..");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading...");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading.");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading..");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading...");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loaded, press any key to continue!");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You're in an empty Room. Would you like to:");
Console.WriteLine("0) Go North");
Console.WriteLine("1) Go East");
Console.WriteLine("2) Go South");
Console.WriteLine("3) Go West");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You've entered a small shop! The items avalible to buy are:");
Console.WriteLine("   ITEM TYPE      | SUBTYPE   |     ITEM COST     |   ITEM DURABILITY   |");
Console.WriteLine("1)     POTION     | strength  |         10        |        3            |");
Console.WriteLine("2)     WEAPON     | club      |         6         |        15           |");
Console.WriteLine("3)      ARMOR     | chestplate|         15        |        13           |");
Console.WriteLine("4)     POTION     | strength  |         8         |        2            |");
Console.WriteLine("5)     WEAPON     | shortsword|         12        |        15           |");
Console.WriteLine("Select the item by pressing it's number, or press 0 to exit");
Console.ReadKey();
Console.Clear();
Console.WriteLine("It looks like you don't have enough money for that item :(");
Console.WriteLine("Press any key to continue");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You've entered a small shop! The items avalible to buy are:");
Console.WriteLine("   ITEM TYPE      | SUBTYPE   |     ITEM COST     |   ITEM DURABILITY   |");
Console.WriteLine("1)     POTION     | strength  |         10        |        3            |");
Console.WriteLine("2)     WEAPON     | club      |         6         |        15           |");
Console.WriteLine("3)      ARMOR     | chestplate|         15        |        13           |");
Console.WriteLine("4)     POTION     | strength  |         8         |        2            |");
Console.WriteLine("5)     WEAPON     | shortsword|         12        |        15           |");
Console.WriteLine("Select the item by pressing it's number, or press 0 to exit");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You've chosen to purchase: ");
Console.WriteLine("   ITEM TYPE      | SUBTYPE   |     ITEM COST     |   ITEM DURABILITY   |");
Console.WriteLine("2)     WEAPON     | club      |         6         |        15           |");
Console.WriteLine("is that correct? press y/n to continue");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You've purchased a Club! Press any key to continue");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You've entered a small shop! The items avalible to buy are:");
Console.WriteLine("   ITEM TYPE      | SUBTYPE   |     ITEM COST     |   ITEM DURABILITY   |");
Console.WriteLine("1)     POTION     | strength  |         10        |        3            |");
Console.WriteLine("2)      ARMOR     | chestplate|         15        |        13           |");
Console.WriteLine("3)     POTION     | strength  |         8         |        2            |");
Console.WriteLine("4)     WEAPON     | shortsword|         12        |        15           |");
Console.WriteLine("Select the item by pressing it's number, or press 0 to exit");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You've left the store, you can:");
Console.WriteLine("0) Go North");
Console.WriteLine("1) Go East");
Console.WriteLine("2) Go South");
Console.WriteLine("3) Go West");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You've entered a room with Enemies!");
Console.WriteLine("     ENEMY TYPE   |   HEALTH   ");
Console.WriteLine("1)     Goblin     |     4      ");
Console.WriteLine("2)      Orc       |     16     ");
Console.WriteLine("Which enemy do you attack?");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Hit! You've dealt 7 damage to");
Console.WriteLine("1)     Goblin     |     4    ");
Console.WriteLine("press any key to continue");
Console.ReadKey();
Console.Clear();
Console.WriteLine("     ENEMY TYPE   |   HEALTH   ");
Console.WriteLine("1)      Orc       |      16    ");
Console.WriteLine("The Orc lunges at you with his club!");
Console.WriteLine("You barely manage to dodge the attack!");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.WriteLine("     ENEMY TYPE   |   HEALTH   ");
Console.WriteLine("1)      Orc       |      16    ");
Console.WriteLine("Which enemy do you attack?");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Hit! You've dealt 13 damage to:");
Console.WriteLine("1)      Orc       |      16    ");
Console.WriteLine("press any key to continue");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.WriteLine("     ENEMY TYPE   |   HEALTH   ");
Console.WriteLine("1)      Orc       |      3     ");
Console.WriteLine("The Orc lunges at you with his club!");
Console.WriteLine("You've been hit, taking 8 points of damage!");
Console.ReadKey();
Console.Clear();
Console.WriteLine("     ENEMY TYPE   |   HEALTH   ");
Console.WriteLine("1)      Orc       |      3     ");
Console.WriteLine("Which enemy do you attack?");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Hit! You've dealt 8 damage to:");
Console.WriteLine("1)      Orc       |      3    ");
Console.WriteLine("press any key to continue");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You've vanquished the monsters!");
Console.WriteLine("You recieve 45 gold. On the ground is:");
Console.WriteLine("   ITEM TYPE      | SUBTYPE   |   ITEM DURABILITY   |");
Console.WriteLine("1)     WEAPON     | DAGGER    |        10           |");
Console.WriteLine("2)     ARMOR      | CHESTPLATE|        13           |");
Console.WriteLine("Select which item you'd like to pick up, or press 0 to continue");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You've chosen to grab:");
Console.WriteLine("1)     WEAPON     | DAGGER    |        10           |");
Console.WriteLine("Is that right? y/n");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You've recieved a new DAGGER!");
Console.WriteLine("Press any key to continue");
Console.ReadKey();
Console.Clear();
Console.WriteLine("On the ground is:");
Console.WriteLine("   ITEM TYPE      | SUBTYPE   |   ITEM DURABILITY   |");
Console.WriteLine("1)     ARMOR      | CHESTPLATE|        13           |");
Console.WriteLine("Select which item you'd like to pick up, or press 0 to continue");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You can:");
Console.WriteLine("0) Go North");
Console.WriteLine("1) Go East");
Console.WriteLine("2) Go South");
Console.WriteLine("3) Go West");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You've entered an empty room");
Console.WriteLine("You can:");
Console.WriteLine("0) Go North");
Console.WriteLine("1) Go East");
Console.WriteLine("2) Go South");
Console.WriteLine("3) Go West");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You've entered a room with stairs! Would you like to decend further into the dungeon? \n y/n");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You've decended to the next level of the dungeon and leveled up!");
Console.WriteLine("Would you like to save the game?");
Console.WriteLine("y/n");
Console.ReadKey();
Console.Clear();
Console.WriteLine("1) Save and continue");
Console.WriteLine("2) Save and exit");
Console.ReadKey();
Console.Clear();