Console.Clear();
Console.WriteLine("Welcome to Himni and Harry's dungeon! \n 0) Load game \n 1) New game");
Console.ReadKey();
Console.Clear();

Console.WriteLine("Game loading");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading.");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading..");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading...");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading.");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading..");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading...");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading.");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading..");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loading...");
Thread.Sleep(250);
Console.Clear();
Console.WriteLine("Game loaded, press any key to continue!");
Console.ReadKey();
Console.Clear();
Console.WriteLine("You're in an empty Room. Would you like to:");
Console.WriteLine("0) Go North");
Console.WriteLine("1) Go East");
Console.WriteLine("2) Go South");
Console.WriteLine("3) Go West");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();
Console.WriteLine("");
Console.ReadKey();
Console.Clear();